"""empty message

Revision ID: bb473e995022
Revises: 9602dc87b24f
Create Date: 2022-05-09 02:19:49.116054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb473e995022'
down_revision = '9602dc87b24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'climate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('climate', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
